namespace BecomingPrepper.Data.Enums
{
    public enum CookingEssentials
    {
        KosherSalt = 1,
        FineSalt = 2,
        BlackPeppercorns = 3,
        ExtraVirginOliveOil = 4,
        VegetableOil = 5,
        AppleCiderVinegar = 6,
        RedWineVinegar = 7,
        BalsamicOrSherryVinegar = 8,
        RiceVinegar = 9,
        BakingSoda = 10,
        BakingPowder = 11,
        CreamOfTartar = 12,
        CocoaPowder = 13,
        ChocolateChipOrBar = 14,
        EvaporatedMilk = 15,
        PureVanillaExtract = 16,
        BayLeaves = 17,
        CajunSeasoning = 18,
        CayennePepper = 19,
        ChilePowder = 20,
        CrushedRedPepper = 21,
        CurryPowder = 22,
        FennelOrDillSeed = 23,
        GranulatedGarlic = 24,
        GroundCinnamon = 25,
        GroundCloves = 26,
        GroundCumin = 27,
        Oregano = 28,
        PaprikaSweetAndSmoked = 29,
        Rosemary = 30,
        SesameSeeds = 31,
        Thyme = 32,
        WholeNutmeg = 33,
        Ketchup = 34,
        Mayonnaise = 35,
        DijonMustard = 36,
        WholeGrainMustard = 37,
        HotSauce = 38,
        WorcestershireSauce = 39,
        SoySauce = 40,
    }
}
